[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
  X-Frame-Options = "SAMEORIGIN"
[build.environment]
  NODE_VERSION = "18"
[[redirects]]
  from = "/practicelibrary/*"
  to = "/:splat"
  status = 200
  force = true
